apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.steamcmd.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.steamcmd.username | quote }}
  password: {{ .Values.steamcmd.password | quote }}
